import "./global.css"
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const inter = Poppins({ weight: "300", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PlainMemo',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.png"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
